name: ag
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - pyarrow
  - matplotlib
  - scipy
  - scikit-learn
  - requests
  - tqdm
  - openpyxl
  - pip:
      - alphagenome
